# Generated by Django 2.2.16 on 2020-10-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=45)),
                ('pw', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
    ]
