# Generated by Django 2.2.16 on 2020-11-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('nowPS', models.IntegerField()),
                ('fullPS', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
