# Generated by Django 2.2.16 on 2020-11-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=45)),
                ('sid', models.CharField(max_length=45)),
                ('contents', models.TextField()),
            ],
        ),
    ]
